return {
 ["content"]={
  ["files"]={
   ["context.exe"]="bin",
   ["context.lua"]="bin",
   ["luametatex.exe"]="bin",
   ["luatex.exe"]="bin",
   ["mtxrun.exe"]="bin",
   ["mtxrun.lua"]="bin",
  },
  ["metadata"]={
   ["directories"]=1,
   ["files"]=6,
   ["path"]="selfautoparent:texmf-win64",
   ["remappings"]=0,
  },
  ["remap"]={},
 },
 ["date"]="2020-04-03",
 ["root"]="selfautoparent:texmf-win64",
 ["time"]="14:46:21",
 ["type"]="files",
 ["uuid"]="8e9f62f0-47c7-8a61-e61e-7712c0442b62",
 ["version"]="1.100",
}